#!/bin/bash
## A script that both runs and intitalizes a gitit repository

set -e

USAGE="$(basename "$0") [-h] [-n NAME] [-p PORT] [-d PATH]

This script provides a convenience wrapper for the 'docker run' command when
using the paullamar3/gitit-pkg image. This script creates a new Gitit
container and then initializes the wiki by copying a folder of markdown 
documents into the container's wiki.

    -h                 Displays this help message.
    -n NAME            The name to assign to the container.
    -p PORT            The host port that Gitit will connect to.
    -d PATH            The folder containing the initialization wiki.

For detailed documentation execute the following to start a Gitit container:
  ./dgititrun 

Attach to the Gitit instance by using a browser to connect to 'localhost'. The 
default Gitit wiki contains pages describing this container image and these
utility shell scripts.

Documentation can also be found at https://github.com/paullamar3/docker-gitit-pkg.
"
# Put current directory in path so we can call other scripts without "./" prefix.
PATH=""$PATH":$PWD"

# First we set up our default values
cname="gitit_$(date +"%j%H%M")"                    # Container Name
port='80'                                          # Host port
dir="$PWD"                                         # Directory with initial wiki

# Parse our options
while getopts ":hn:p:d:" opt; do
  case $opt in
    h)
      echo "$USAGE"
      exit
      ;;
    n)
      cname="$OPTARG"
      ;;
    p)
      port="$OPTARG"
      ;;
    d)
      dir="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      ;;
  esac
done

# This is the name for our initialization container
cinit=""$cname"_init"

# Now run the Gitit container
dgititrun -n "$cname" -p "$port" || { echo "Failed run of Gitit container." >&2; exit 1; }
dgititrun -n "$cinit" -i "$cname" -d "$dir" -x 'clone' || { echo "Failed run of initialization container." >&2; exit 1; }

echo "Gitit container is running and initialized."

